#!/bin/bash

echo "파일/디렉토리 이름 입력:"
read fname

if [ ! -e "$fname" ]; then
    echo "존재하지 않습니다."

elif [ -f "$fname" ]; then
    echo "보통파일 입니다."

elif [ -d "$fname" ]; then
    echo "디렉토리 입니다."

elif [ -L "$fname" ]; then
    echo "심볼릭링크 입니다."

elif [ -p "$fname" ]; then
    echo "파이프 입니다."

elif [ -S "$fname" ]; then
    echo "소켓 입니다."

elif [ -b "$fname" ]; then
    echo "블록장치 입니다."

elif [ -c "$fname" ]; then
    echo "문자장치 입니다."

fi
